### ISSUE TITLE
Add responsiveness to the whole site

### ISSUE THREAD

**Issue by sarthakk24** [SauveJeanLuc/coffee-tasks#72] opened 2022-10-06 16:40 UTC
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] responsiveness is not good at the moment

**To Reproduce** \
1. Go to browser console

**Possible solutions** (Optional) \
Add responsiveness using tailwind css

**Screenshots**
![screencapture-coffeetasks-netlify-app-2022-10-06-22_10_22](https://user-images.githubusercontent.com/70757536/194370331-c893d35b-6266-41c8-9c3a-bc2e4bc85c79.png)

**Comment by sarthakk24** [comment] 2022-10-06 16:42
Alse if you want me to work on this issue please assign it to me and add the hacktoberfest tag 
Thank you :)

**Comment by SauveJeanLuc** [comment] 2022-10-06 20:04
Isn't this a duplicate of #61 ?

**Closed** 2022-10-08 18:39 UTC
